apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/jarvis-401/viction-mainnet.git
    path: charts/prometheus/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: false          
      selfHeal: true         
    syncOptions:
      - CreateNamespace=true 
